### ISSUE TITLE
UI components need to enable installing of schemas into Sanity

### ISSUE THREAD

**Issue by readeral** [NewFrontDoor/ui#79]
Sanity extensions/plugins require a number of things for them to work:
- A sanity.json file at the root of the package alongside the package.json
- Wants to be able to find schema files with a definitive path

See an example here: https://github.com/rexxars/sanity-plugin-markdown/blob/master/sanity.json
See the documentation on the sanity.json file here: https://www.sanity.io/docs/sanity-json

At the moment, our microbundler approach bundles all files together based on index.js and whatever is imported/exported there, and so the final bundle does not preserve the schema files, nor does it capture up the sanity.json file.

We will need some other solution to allow Sanity schemas for each UI component to be installable according to Sanity's requirements.

**Comment by BarryThePenguin** [comment]
The best we can do is add a second script to compile the schema files.. something like

```js
"prepare": "microbundle --no-compress && babel -d dist/schemas src/schemas"
```

**Comment by readeral** [comment]
@BarryThePenguin could you have a crack at rigging this up?

**Comment by BarryThePenguin** [comment]
It appeared to work when I tried it. This is the line I updated

https://github.com/NewFrontDoor/ui/blob/df76f22868166807b203ef45c4f95c3d4ccf1fd0/packages/form/package.json#L9

I'm not sure how to verify the result. You'll need to do that

**Comment by readeral** [comment]
So adding `&& babel -d dist/schemas src/schemas` works for creating the folder of files we need, but we need the sanity.json file too. I've tried the --copy-files argument, but it doesn't have any effect

**Comment by BarryThePenguin** [comment]
Does the `sanity.json` file need to be relative to specific directory? Sounded like it just needs to be in the same directory as the `package.json` file

**Comment by readeral** [comment]
nope, just in the package.json directory. It's the schemas that need to be accurately found by the directions of the sanity.json file.

**Comment by BarryThePenguin** [comment]
Then it doesn't need to move anywhere

**Comment by readeral** [comment]
It doesn't need to be bundled up in the dist folder?

**Comment by readeral** [comment]
Also, can we exclude the schemas from the bundled files?

**Comment by BarryThePenguin** [comment]
> It doesn't need to be bundled up in the dist folder?

I'm not aware of why it would need to be?

> Also, can we exclude the schemas from the bundled files?

I thought the point of this issue _was_ to bundle the schema files?

**Comment by readeral** [comment]
When we install the component - Sanity wants to see the sanity.json file in the root. At the moment, that file isn't in dist - so it won't be in an installed package.

By excluding the schema files I mean not being compiled into the index.js file, as they are being copied separately in the schemas folder.

**Comment by BarryThePenguin** [comment]
You can run `yarn prepare && yarn pack` from a package directory to see exactly what will be included in an installed package. It generates a `.tgz` file you can inspect

If you want to include additional files, you can add them to the `files` array in the `package.json`. Currently we just include the `dist` directory.

> By excluding the schema files I mean not being compiled into the index.js file, as they are being copied separately in the schemas folder.

If you don't want them bundled in the `index.js`, you can remove their import statements 

https://github.com/NewFrontDoor/ui/blob/df76f22868166807b203ef45c4f95c3d4ccf1fd0/packages/form/src/index.js#L6-L8

**Comment by readeral** [comment]
Right. Yes. That's all we need.

**Comment by readeral** [comment]
Hmm apparently we still need the `&& babel -d dist/schemas src/schemas` to make it work. I just had to re-add it back in to ensure that changes to the schema were included in my next release
